[package]
name = "mayon_c_api"
version = "0.1.0"
edition = "2024"

[lib]
name = "mayon"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
# internal crates
mayon = { path = "../mayon", features = ["allocator"] }

# workspace crates

[build-dependencies]
cbindgen = "0.29.2"
