[package]
name = "helper_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = { workspace = true, features = ["full"] }
quote.workspace = true
proc-macro2.workspace = true
