[package]
name = "mayon"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[features]
default = ["error_location"]
error_location = []

[dependencies]
# internal crates
mayon_core.path = "../core"
mayon_vulkan_backend.path = "../mayon_vulkan_backend"
